# Generated by Django 4.1.7 on 2023-03-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='allowed_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
