# Generated by Django 4.1.5 on 2023-02-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='allowed_params',
            field=models.JSONField(default='test_price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='params',
            field=models.JSONField(default='test____price'),
            preserve_default=False,
        ),
    ]
