# Generated by Django 4.1.7 on 2023-05-26 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0002_ratingreviewsbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('status', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ratingreviewsbookmark',
            options={'verbose_name': 'Отзывы рейтинг и закладки', 'verbose_name_plural': 'Отзывы рейтинг и закладки'},
        ),
        migrations.AlterField(
            model_name='ratingreviewsbookmark',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RatingReviewsBookmark', to='objects.item'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.order')),
            ],
        ),
    ]
