# Generated by Django 4.1.5 on 2023-02-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_remove_item_price_category_allowed_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='allowed_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
