# Generated by Django 4.1.7 on 2023-05-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_order_alter_ratingreviewsbookmark_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
