# Generated by Django 4.1.7 on 2023-05-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_orderitem_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
    ]
